### PR TITLE
Added my 2nd, 3rd, 4th, 5th, summary reflection, 7th, & 8th week reflection and collaboration article

### PR DESCRIPTION
**Pull request by r-ayaay**
Added my reflection on my 2nd week interning here, which describes my experience using laravel, the CLI, and exploring the project. an image associated with this reflection is also included.

### CODE REVIEW

**Comment by r-ayaay** [comment]
UPDATED: added collaboration article which contains our experiences and journey in programming

**Comment by r-ayaay** [comment]
Update: added my reflection on today's (friday, aug 25) topic: applying effective bug reporting

**Comment by r-ayaay** [comment]
Update: Added 4th week friday reflection which contains details and my experience on:
- effectively reporting bugs and properly verifying
- SSH

**Comment by r-ayaay** [comment]
added 8th week reflection which contains details and my experience on:
- cron
- regex
- laravel events & listeners

**Review by ardiesan — APPROVED** [review]

**Pull request merged**
